#!/bin/bash

POPPLER_VERSION=${POPPLER_VERSION-22.07.0}
POPPLER_TARBALL_URL="https://poppler.freedesktop.org/poppler-${POPPLER_VERSION}.tar.xz"
TEMP_DIR=$(mktemp -d /tmp/poppler.XXXXXXXXXX)

#if ! [ -x "$(command -v xc)" ]; then
#  export DEBIAN_FRONTEND=noninteractive
#  apt-get update
#  apt-get install -y xz-utils
#fi

echo "Serving files from /tmp on $PORT"
cd /tmp
python -m SimpleHTTPServer $PORT &

cd $TEMP_DIR
echo "Temp dir: $TEMP_DIR"

echo "Downloading $POPPLER_TARBALL_URL"
curl -L $POPPLER_TARBALL_URL | tar xJ

(
	cd poppler-${POPPLER_VERSION}
	mkdir build
	cd build
	cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/poppler -DCMAKE_BUILD_TYPE=release -DENABLE_BOOST=OFF -DENABLE_LIBOPENJPEG=none -DBUILD_SHARED_LIBS=OFF
	make
	make install
)

cp /tmp/poppler/bin/pdftotext $1
